### ISSUE TITLE
Archived RedZone not showing up in int'l GP?

### ISSUE THREAD

**Issue by salvatoreorange** [aqw/xbmc-gamepass#279] opened 2016-10-30 01:20 UTC
Hi guys, very helpful add-on! 

Just an observation that archived RedZone is not showing up for international game pass currently. The browser viewing experience is god-awful in comparison, so I am desperate to watch it through your add-on. : )

Thank you!

**Comment by salvatoreorange** [comment] 2016-10-30 01:22
Haha! My mistake - I just noticed an archived RedZone post on the "Code" tab. All good.

**Comment by salvatoreorange** [comment] 2016-10-30 01:46
(Updating to reopen)

**Comment by aqw** [comment] 2016-11-02 10:29
@salvatoreorange Whoops, didn't realize you had this issue open. I'll copy and paste for completeness:

"What's not working for you? I have an international subscription and see the RedZone Archives (and they play). NFL Network -> 2016 -> RedZone Archives"

---Alex

**Comment by salvatoreorange** [comment] 2016-11-02 12:11
Hi there, this is what my menu for NFL Network 2016 looks like right now: http://imgur.com/vOTy52v

**Comment by aqw** [comment] 2016-11-02 12:15
@salvatoreorange That... is odd. Can you provide a debug log? Where are you geographically located?

---Alex

**Comment by salvatoreorange** [comment] 2016-11-02 12:16
I'm in Australia. Sure - I have debugging active in the add-on, but not sure where to find the file?

**Comment by aqw** [comment] 2016-11-02 12:18
Kodi has some instructions here: http://kodi.wiki/view/Log_file

---Alex

**Comment by aqw** [comment] 2016-11-02 12:19
@salvatoreorange Ahh, also, be sure to enable debugging in *both* Kodi and the addon's settings.

---Alex

**Comment by salvatoreorange** [comment] 2016-11-02 12:29
https://paste.ubuntu.com/23415891/

**Comment by aqw** [comment] 2016-11-02 12:42
@salvatoreorange I forgot that we had recently fixed this bug (apparently my brain is still on vacation ;-). It's fixed in latest master, so you're welcome to use that. Or, if you're ok with waiting, I'll cut a release within a week and it'll update through the normal Kodi channels.

Thanks for the log. :-)

---Alex

**Comment by salvatoreorange** [comment] 2016-11-02 12:57
Thanks for that! I have downloaded the master files and briefly tested - RedZone archives show up now but nothing happens when I click any of them (loads for a couple secs, then nothing). I will mess with it some more tomorrow, but thanks again for the help. : )

**Comment by aqw** [comment] 2016-11-02 13:12
@salvatoreorange That happened to me once while testing today. Worked every time after that. Perhaps Game Pass is having some hiccups right now.

Be sure to restart Kodi to clear any caches, etc.

---Alex

**Comment by salvatoreorange** [comment] 2016-11-03 10:47
Hi Alex, I tried again today and none of the RedZone archives are actually working when I click on them. There's always that 1-2 second loading period followed by nothing. 

I've uploaded another log file, if it might help to identify the issue: https://paste.ubuntu.com/23420188/

**Comment by aqw** [comment] 2016-11-03 13:01
@salvatoreorange Hmmm, do other streams play? I see the following in the log:


    21:42:07 T:14884   ERROR: CCurlFile::GetCookies - invalid cookie: '.neulion.com	TRUE	/	FALSE	0	nl	'

Which would be... bad.

---Alex

**Comment by salvatoreorange** [comment] 2016-11-03 13:26
Game archives play fine, it seems to just be items in the NFL Network header, like only some of the "A Football Life" programs play, for example (only in 2016, none of those in 2015 will play), and obviously none of the RZ archives will play either.

**Comment by salvatoreorange** [comment] 2016-11-17 23:33
I decided on a whim yesterday to check out the Android version of Kodi (along with this add-on), and surprisingly, programs I previously couldn't watch on desktop (A Football Life eps from 2015, random Super Bowl archives) worked without any problem at all.

I am curious, Alex, do you have any idea as to what would be preventing these programs from playing on desktop Kodi? I have already deleted all the cache and cookies files i could find in the Kodi directory, didn't fix anything, you click the program, it loads for a sec, then nothing happens. 

I am dying to troubleshoot this (as I am completely convinced it'd fix RZ archives for me as well, which is my real goal). Just not sure where to start.

**Comment by aqw** [comment] 2016-11-18 09:49
@salvatoreorange I have no idea what is causing this behavior. And other than the once, I have been unable to reproduce it. Are you using any proxies or something funky like that? That could cause these issues.

---Alex

**Comment by salvatoreorange** [comment] 2016-11-18 12:43
Not at all. I'll keep trying things.

**Comment by salvatoreorange** [comment] 2017-01-06 02:08
Hey Alex,

I am indeed still having this problem. I was never able to figure it out (I simply stopped watching RedZone - lol).

Regardless, I appreciate your assistance in this thread! Hopefully by next regular season, whatever build is out will have resolved my issue. : )

**Comment by aqw** [comment] 2017-08-14 10:45
Closing this issue, as it's stale and the services have changed so much, it's likely no longer relevant.

---Alex

**Closed by aqw** 2017-08-14 10:45 UTC
