### ISSUE TITLE
Unable to click through to any weeks, in any year.

### ISSUE THREAD

**Issue by james-dowling** [aqw/xbmc-gamepass#336] opened 2017-08-24 09:59 UTC
I get "unexpected error ='(."

I enabled debugging, and the error seems to be in pigskin.py line 225. It's trying to index into a dictionary, using a key ("content") which isn't in the response of a successful week listing from the nfl server. Perhaps they've updated their response schema?

Relevant log below:
https://pastebin.com/fbHzFAQ4

**Comment by kaileu** [comment] 2017-08-24 10:00
This issue is fixed in the current master.

Mit freundlichen Grüßen
Kai Leutner

**Comment by emilsvennesson** [comment] 2017-08-24 10:01
@kaileu is right, this has been fixed by commit https://github.com/aqw/xbmc-gamepass/commit/6e9ed50c0e95cc8bcad20848fe022ac08501dd44. Closing as this is a dupe of #330 and #331.

**Closed by emilsvennesson** 2017-08-24 10:01 UTC
Labels: duplicate

**Comment by emilsvennesson** [comment] 2017-08-24 10:05
@aqw What do you think about releasing a 0.11.2 version seeing as the latest release seems to be completely defunct?

**Comment by aqw** [comment] 2017-08-24 10:12
@emilsvennesson Yeah, I should do that. I just havn't had the time until now. I'll get that done today.

---Alex

**Comment by aqw** [comment] 2017-08-24 16:04
@kaileu I should have asked before: any proposals for a 0.11.1 release name? You did the main body of feature-work for the 0.11.0 release, but the "Jay Cutler" moniker was just too fitting to cast aside. ;-)

This release is all yours to name. So choose wisely... ;-)

---Alex

**Comment by kaileu** [comment] 2017-08-24 16:12
Did we had a Kenny Easley edition?

Mit freundlichen Grüßen
Kai Leutner

**Comment by Ghoschdi** [comment] 2017-08-24 16:22
Just a quick one: Do you have a list of all your past release names? I would really love to dedicate the next major release - maybe the one which also brings back international support, to the passed Cortez Kennedy if he has not been picked before, so need to find out who i need to get some beers to do that :)

**Comment by aqw** [comment] 2017-08-24 17:15
@kaileu Then Kenny Easley edition it shall be. :-)

@Ghoschdi The release history and names are in master/changelog.txt. You've helped so much with bug triaging, there's no need for the beer bribe. ;-) The "Cortez Kennedy" Edition will be in the imminent future. Remind me as the next release approaches, to make sure I don't forget. :-)

---Alex

**Comment by aqw** [comment] 2017-08-24 20:00
The release is out. :-)

Kodi devs merged it super fast. :-)

---Alex

**Comment by ShonKable** [comment] 2017-08-24 21:52
Aqw... are you speaking about 11.1.. is it out?

**Comment by aqw** [comment] 2017-08-25 06:04
@ShonKable Yes, 0.11.1 is in the Kodi repos.

---Alex

**Comment by ShonKable** [comment] 2017-08-25 11:44
![screenshot_20170825-073739](https://user-images.githubusercontent.com/31002673/29712700-1f5923b0-8969-11e7-8f0c-7b7b829ddb6b.png)

**Comment by ShonKable** [comment] 2017-08-25 11:45
Im in the US and this is what i get with a valid log in account?

**Comment by kaileu** [comment] 2017-08-25 11:47
At the moment we only support Gamepass Europe. Gamepass International which includes the US is not supported at the moment.
Sean Arnold is working at the implementation.


Mit freundlichen Grüßen
Kai Leutner

**Comment by ShonKable** [comment] 2017-08-26 11:56
Trying to get in touch qith Mr. Sean Arnold.. please contact me directly @ShonKable@mail.com.  thx

**Comment by aqw** [comment] 2017-08-26 12:04
@ShonKable Unless you're going to help Sean Arnold develop support, the only thing you're going to do is distract him from the work you're hoping for him to do.

---Alex

**Comment by kaileu** [comment] 2017-08-26 12:07
And if you want to support development https://github.com/seanarnold/xbmc-gamepass
