### ISSUE TITLE
Kodi 17 (Krypton) support

### ISSUE THREAD

**Issue by Donl5355** [aqw/xbmc-gamepass#234] opened 2016-06-06 21:05 UTC
Hey when i try to install your addon (from zip, because its not in the repository anymore) i get this error message "The dependency on xbmc.gui version 5.10.0 could not be satisfied.". Thanks anyways and great addon.

**Comment by kaileu** [comment] 2016-06-07 03:38
Kodi Kryption is not a stable Kodi version so use Kodi 16 and it will work ;-)

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2016-06-07 07:31
@Donl5355 Thanks for the bug report. This addon isn't in the Krypton repo yet because no one has tested it and made the necessary API adjustments. Kodi changes its skin API nearly every release, so sometimes it can take some real effort to update it to work.

Other times, the upstream changes are minor, and it's as simple as editing addon.xml and changing the required xbmc.gui version number.

According to [this page](http://kodi.wiki/view/Kodi_v17_%28Krypton%29_changelog), Krypton's .gui version string is 5.11.0 (though [this page](http://forum.kodi.tv/showthread.php?tid=250862) says it's 5.12.0 now, and looks more up-to-date). Try changing that, and it may work for you.

---Alex

**Comment by Alexqw** [comment] 2016-06-07 07:43
This one might affect us: https://github.com/xbmc/xbmc/pull/9114

**Comment by kaileu** [comment] 2016-06-07 08:14
This one might affect us also: https://github.com/xbmc/xbmc/pull/9286
At the current stage it doesn't but we will see if this is going on.

**Comment by Alexqw** [comment] 2016-06-07 08:24
They seem to be breaking/changing a lot with this release.

**Comment by Donl5355** [comment] 2016-06-07 14:37
I changed xbmc.gui in the addon.xml to 5.12.0 and now it works.

**Comment by kaileu** [comment] 2016-06-07 14:41
Yes it did but it may break again because there is a mayor change  
which are not in the current build.

Mit freundlichen Grüßen
Kai Leutner

**Comment by kaileu** [comment] 2016-06-14 13:03
The new VideoPlayer uses a new system https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_dll.h with this its possible to compile binary Addons which supports different Codecs.
Mapfau https://github.com/mapfau/inputstream.mpd implemented a DASH Version.
Maybe we can use it to implement the remaining features like adaptive Streaming, Playing from Begin, multiple AudioStreams etc...

Maybe its interessting for someone who can programming cpp or if another Project like one of https://github.com/eracknaphobia will implement this.

**Comment by Displayel** [comment] 2016-07-10 17:23
i have a question regarding the great Game Pass addon, i recently upgraded to a LG 4k TV and also upgraded my Set Top Box to an Nvidia Shield, now when i play some old games on Kodi either 16.1 or Krypton 17 Alpha 2 i have this micro stutters that really make the viewing experience suffer, is this a issue by the NFL for not providing 60 fps or what could be the issue ?

**Comment by Alexqw** [comment] 2016-07-11 09:11
@Displayel Your problem likely has nothing to do with Krypton support.

I don't know how powerful the Nvidia Shield is, but you should try playing around with the hardware acceleration settings and see if that helps you.

---Alex

**Comment by Displayel** [comment] 2016-07-11 15:05
its the most powerful box on the market right now, i found an interesting piece from users who upgraded to the shield to firmware 3.2 that this update broke the deinterlacing and they wait for a fix, is deinterlacing important for live or recorded feeds ?

**Comment by Alexqw** [comment] 2016-07-11 16:28
@Displayel It all depends on the streams, as they can vary. I really can't remember if GamePass provides 1080p or 1080i...

@BaumSchorle or anyone else remember off-hand?

---Alex

**Comment by dahlSTROM** [comment] 2016-07-11 17:13
I'm pretty sure all streams from Game Pass are progressive.

This one will probably break live streams in Krypton: xbmc/xbmc#9330

**Comment by Alexqw** [comment] 2016-07-11 17:19
@dahlSTROM That's what I thought I remembered, but isn't our skin technically listed as 1080i? Maybe I'm just blathering BS at this point. It's been quite the day... (or for that matter, a month...)

---Alex

**Comment by emilsvennesson** [comment] 2016-07-11 18:26
@Alexqw Yeah, I think we did it that way because Kodi doesn't look for its skin files in a 1080p directory for some reason. FYI, I just changed my GitHub username!

**Comment by kaileu** [comment] 2016-07-11 18:56
I didn't notice any stuttering on the current nvidia shield version.

Mit freundlichen Grüßen
Kai Leutner

**Comment by kaileu** [comment] 2016-07-11 18:56
I didn't notice any stuttering on the current nvidia shield version.

Mit freundlichen Grüßen
Kai Leutner

**Comment by CraigMack69** [comment] 2016-07-11 19:19
Look forward to seeing what changes come rolling this year. Been using for like 3-4 years now and having seen this project from its early stages to now,are incredible :)
If any of you devs need an account for testing let me know please. I can and will provide them for this addons testing

**Comment by Alexqw** [comment] 2016-07-11 21:04
@emilsvennesson Ahh. That (1080p vs 1080i) does sounds familiar now... and thanks for the heads up with the username change. I was confused for a moment there. ;-)

@CraigMack69 Thanks for the support/offer. Most (all?) devs have accounts of our own, so that's not much of a concern. But if you or anyone else is in the US and has some coding/debugging chops, that'd be a huge help, as that is our biggest blind spot at the moment.

---Alex

**Comment by Displayel** [comment] 2016-07-12 15:39
on a 4K TV Kaileu ? because i have no issues on a Full HD TV

**Comment by kaileu** [comment] 2016-07-12 17:47
Ok no i didn't have a 4k tv so this is only relevant for 4k tvs so no  
addon related Problem.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment] 2016-07-13 14:06
is anyone reading what i´m writing at all ??? Sorry i mentioned twice now if this could be a 60fps problem, because this is only offered with Xbox One ???

**Comment by BaumSchorle** [comment] 2016-07-13 14:23
@Displayel cool down, all of the devs are doing this for free, beside their normal jobs and families.

Your problem could be caused by a lot of things: 

- your TV 
- your Kodi settings
- the fact that Games are not provided in 60fps
- ...

However it is definitely no problem with the addon, because we are just handing the url of the stream to ffmpeg, whatever happens then is not our fault or in our hand!

**Comment by Displayel** [comment] 2016-07-13 14:27
i´m cool.....i figure it is the 60fps issue, i have all the settings trough in kodi, nothing helps, i never thought the problem would be the addon, i know you guys are just putting out what the NFL offers, but since i have no problem with other US Live TV Channels it must be the 60fps issue

**Comment by Alexqw** [comment] 2016-07-14 09:31
@Displayel 60 fps is almost certainly not the issue. And @BaumSchorle is right that there's basically nothing we can do.

Something that I alluded to before is whether your hardware (because I know nothing about it) has the capacity to drive 4k resolution from an encrypted internet stream while upscaling that HD stream to 4k. That's a lot of work for a tiny box to do at once. And, since you indicated it only happened on some older games, it could be that those older games are encoded in a way that doesn't quite offload as well to the hardware acceleration as other games do. I would expect the problems to go away by only pushing 1080p to the 4k TV rather than having the box upscale 1080p to 4k.

---Alex

**Comment by Displayel** [comment] 2016-07-14 13:56
but the thing is i have no problems watching live TV from the US with another kodi addon, so i thought the 60fps might be the issue here, maybe its only the old games and it goes away when the live games are starting in september

**Comment by Alexqw** [comment] 2016-08-01 11:24
I've been reading through some of the [API](http://forum.kodi.tv/showthread.php?tid=250936&page=2) and [GUI](http://forum.kodi.tv/showthread.php?tid=250862) changes for Krypton; a few things I noticed:
* changelog is now the <news> tag in addon.xml
* fanart and icon must be declared in the [new <asset> tag](http://forum.kodi.tv/showthread.php?tid=250862&pid=2376263#pid2376263) in addon.xml (but as a plus, can now be located anywhere)
* some nice changes to dialogs that might be useful
* default skin is now estuary, so if there's font changes, we need to match that
* Setting properties on WindowXML is now [more convenient](http://forum.kodi.tv/showthread.php?tid=250936&pid=2259905#pid2259905)
* IsEmpty() is [deprecated](http://forum.kodi.tv/showthread.php?tid=250862&pid=2281321#pid2281321)

Once they start rolling out Beta releases, then I think it makes sense to start working on these.

---Alex

**Comment by Alexqw** [comment] 2016-08-01 14:00
Also, in order to reduce addon spamming in the Kodi log, all addon logging will be redirected to the debug log. Thus, there's no longer much use for a debug wrapper function.

**Comment by Ghoschdi** [comment] 2016-08-04 08:45
Just a quick add: I have a Philips 4k TV, NVIDIA Shield TV Box and use Gamepass in 0.91 with the modified addon.xml. Works like a charm, no stutters or any performance issues on archived games. So the issues has is surely located somewhere else.

**Comment by Alexqw** [comment] 2016-08-04 08:55
@Ghoschdi Nice, thanks for the info.

---Alex

**Comment by codebakery-ch** [comment] 2016-08-05 13:32
Tested it on a new Sony model with Android TV. No issues, just had to manually add the xmltodict AddOn. Seems to be even a bit more responsive/faster...

**Comment by chovy** [comment] 2016-08-06 03:51
fyi: kodi 17.x will ship with ffmpeg 3.0 -- I am unable to play neulion streams with ffmpeg 3.x -- if I downgrade to ffmpeg 2.8.5 they play fine.

I'm using the same logic to play individual NFL Network stream from this addon. It does *not* work with ffmpeg 3. I'm wondering if anyone has noticed this problem or has a solution?

**Comment by Alexqw** [comment] 2016-08-06 08:06
@chovy At first I was skeptical, but then I found [this bug](https://trac.ffmpeg.org/ticket/5248). So, if you can compare your log with the output in that bug and it's a match, then you should definitely open a bug with Kodi, referencing the ffmpeg bug report.

Definitely a big deal.

---Alex

**Comment by chovy** [comment] 2016-08-06 19:33
I'm still seeing it with NFL/NBA

**Comment by Alexqw** [comment] 2016-08-06 19:34
@chovy Seeing what?

**Comment by chovy** [comment] 2016-08-06 19:35
neulion streams start up fine but as soon as the first key request is made it returns a 403. If I downgrade to 2.8.x it works fine.

**Comment by BaumSchorle** [comment] 2016-08-06 19:40
Could be because of this: https://github.com/xbmc/xbmc/pull/9330

We need to pass a lot of info in the header!

**Comment by Alexqw** [comment] 2016-08-06 19:42
@chovy OK. Did you read my previous comment where I pointed out an ffmpeg bug report detailing exactly that? And my suggestion that you compare your logs to the output in that bug report, and if it's a match, then you should report the bug to the Kodi devs?

ffmpeg is not part of this addon; it's part of Kodi. It's a kodi problem; they should be made aware. It will affect all encrypted HLS streams.

---Alex

**Comment by chovy** [comment] 2016-08-06 19:44
Yes, I looked at your bug, it says it was "fixed" in March. I'm still seeing it even when I call ffmpeg 3.x manually. I don't believe the bug is related to kodi at all since I can reproduce it against ffmpeg. I have tried to find others who have problems with Neulion streams, but this plugin is one of the only few I know that use it.

**Comment by Alexqw** [comment] 2016-08-06 19:47
@chovy You do realize that it's "fixed" in ffmpeg master. That doesn't necessarily mean that the version of ffmpeg bundled in Kodi includes the patch.

And it sounds like you're using your own ffmpeg, independent of Kodi? That'd be nice to know upfront for troubleshooting... are you using latest ffmpeg master? If you want any help you're going to have to be way more specific. Otherwise you're coming across like you expect to me divine a solution with no background info and no logs.

**Comment by chovy** [comment] 2016-08-06 19:49
It should have been released by now. ffmpeg 3.1.1 is out.

**Comment by chovy** [comment] 2016-08-07 21:50
My apologies. I was hoping I wasn't the first one to notice this issue between ffmpeg 2.8 and 3.1 so I didn't bother posting all the details. Here is an example ffmpeg command with 3.1.1


	ffmpeg -re -y -threads 8 -user-agent 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H143' -headers 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H143' -cookies 'nlqptid=nltid=nflgp&nltdt=6&nltnt=1&uid=685652&hdnea=expires%3D1470606402%7Eaccess%3D%2Fnlds%2Fnfl%2Fnfltv%2Fas%2Flive%2F*%7Emd5%3D6ff1144a2746e5c796d3b2501d88a26d path=/; domain=nlds21.cdnak.neulion.com;' -i http://nlds21.cdnak.neulion.com/nlds/nfl/nfltv/as/live/nfltv_hd_2400.m3u8?nltid=nflgp\&nltdt=6\&nltnt=1\&uid=685652\&hdnea=expires%3D1470606402%7Eaccess%3D%2Fnlds%2Fnfl%2Fnfltv%2Fas%2Flive%2F\*%7Emd5%3D6ff1144a2746e5c796d3b2501d88a26d -bufsize 10 -hls_time 10 -hls_list_size 10 -hls_wrap 10 -ignore_unknown -hls_flags delete_segments -hls_segment_filename /home/username/data/streams/nfl-nfltv/video%03d.ts -c copy /home/username/data/streams/nfl-nfltv/index.m3u8


	after the first key request I get a 403 forbidden error:

	Press [q] to stop, [?] for help
	frame= 2098 fps= 30 q=-1.0 size=N/A time=00:01:10.03 bitrate=N/A speed=0.998x   [http @ 0x4a0c700] HTTP error 403 Forbidden:01:49.99 bitrate=N/A speed=   1x
	Unable to open key file http://nlsk.neulion.com/nlsk1/hls/securekey?id=21&url=/nlds/nfl/nfltv/as/live/nfltv_hd_2400/20160807214000.m3u8.key


	This works fine on ffmpeg 2.8.x but not with ffmpeg 3.1.1


I'm assuming not a lot of people have noticed this yet since Kodi 16.1 still ships with ffmpeg 2.8.x

**Comment by Alexqw** [comment] 2016-08-08 08:38
@chovy Thank you for providing more information.

The 403 is what surprises me here. It sounds like ffmpeg isn't passing along cookies or other necessary information when retrieving a key. Maybe they re-regressed [this bug](https://trac.ffmpeg.org/ticket/4846)?

I recommend playing with your favorite sniffer and comparing the cookies and/or user agents that are sent throughout the lifetime of the stream. I think the bug will become pretty apparent at that point.

---Alex

**Comment by Ghoschdi** [comment] 2016-08-08 09:19
I use the latest Kodi 17 Alpha3 and have no issues with the shipped ffmpeg 3.1.1 build neither on the Shield (Android TV) nor on my windows machines. I watched 3 full 2015 games yesterday and gave it another try just now to test again, no issues after 15 minutes of streaming. Unfortunately no MAC powered devices to test that.

**Comment by Alexqw** [comment] 2016-08-08 09:23
@Ghoschdi Thanks for the info! That is reassuring.

@chovy What OS/distro are you using? Is the 3.x ffmpeg hand rolled or provided by the distro?

---Alex

**Comment by chovy** [comment] 2016-08-09 09:57
@Ghoschdi that's not surprising. Those aren't live streams. This dropped key request seems to be an issue with m3u8 live streams. That being said, can you watch NFL Network for an extended period of time (15 minutes minimum) using Kodi 17/ffmpeg 3.1?

**Comment by chovy** [comment] 2016-08-09 20:57
@Ghoschdi I'm using international too. One thing, are you set to "ask" for which quality stream? I'm playing an individual stream (ie: 3000k) -- might be the one difference.

**Comment by Ghoschdi** [comment] 2016-08-09 21:16
I set to ask and tested 3k. Same results. 
![screenshot 2016-08-09 23 16 28](https://cloud.githubusercontent.com/assets/10353742/17533946/533e7bde-5e87-11e6-9acf-d03bd17883ec.png)

Are you physically located outside of US or are you using a proxy to use international? You should not be able to use international inside of US with regular internet access.

**Comment by chovy** [comment] 2016-08-10 00:38
@Ghoschdi yes, i'm in US but using a proxy. I don't think that's the issue because it plays  fine with ffmpeg 2.8.6 -- its only 3.1.1 that doesn't work. Anyway, it must be something on my end. Weird.

**Comment by Alexqw** [comment] 2016-08-10 08:33
@chovy @Ghoschdi Very odd indeed. This could be the fault of the proxy, and perhaps there was a regression in ffmpeg where it's not passing along enough of the parameters. But that is a bit of a stretch.

@chovy Did you get a chance to analyze the traffic? I think that's the only way you're going to figure out what is actually going on.

@Ghoschdi To answer a few of your questions: as far as we know, both Domestic and International are identical (services, encryption, XML responses, etc) except for blackouts of games and likely also the actual geographic location of the streaming server. Replays are unencrypted but live games (and RedZone and NFL Network) are encrypted. @chovy does what most US subscribers we know of do: purchase access to a proxy outside of the US to authenticate and thus avoid the blackouts. This is unsupported by us, but it isn't entirely clear yet (though I am beginning to strongly suspect) that his problem is somehow due to that. So we explore the problem until we confirm one way or another.

---Alex

**Comment by chovy** [comment] 2016-08-10 16:12
@Alexqw what type of traffic analysis should I do? I can certainly try with a different smartdns, I have a few.

**Comment by Alexqw** [comment] 2016-08-10 20:25
@chovy Wireshark and/or Fiddler are both well suited to capturing and examining this type of network traffic.

---Alex

**Comment by basrieter** [comment] 2016-08-31 18:39
Any success in passing http headers to ffmpeg from Kodi Krypton? It indeed seems that https://github.com/xbmc/xbmc/pull/9330 broke this?

**Comment by anthonyettinger** [comment] 2016-08-31 18:47
I've tried playing the stream with just a standard ffmpeg command. It does not work in 3.1.x only in 2.8.x for me.

**Comment by basrieter** [comment] 2016-08-31 18:49
But in general, passing http headers to Kodi so they are used by ffmpeg?

**Comment by aqw** [comment] 2016-09-02 08:14
@basrieter I'm currently using Kodi 16, so I don't have any first hand experience with 17. But I know of a few people running this addon with Kodi 17 and they report that it works. @anthonyettinger Has been experiencing some problem with headers, but I'm not quite sure what's going on in his case. IIRC, it seemed that he was passing the streams to a separate build of ffmpeg outside of Kodi, so it's a bit out of scope for us.

Are you using this addon with Kodi 17 and having troubles with streams?

---Alex

**Comment by basrieter** [comment] 2016-09-02 08:25
No, as and  add-on dev myself I was running into the http header issue myself and the conclusion is that within Kodi Krypton, http headers aren't passed on to ffmpeg anymore, which basically breaks a lot of add-ons. it sucks.

**Comment by aqw** [comment] 2016-09-02 10:32
@basrieter Ahh, I didn't realize you were also a dev and were asking if we'd been bitten by this.

TBH, I'm surprised Kodi would make a change like this intentionally. Also, what is confusing to me is that @Ghoschdi isn't seeing the problem (and he's running Krypton IIRC).

All I can say is we aren't doing anything special (yet), and I hope the Kodi devs see the light and fix/un-break this.

---Alex

**Comment by Ghoschdi** [comment] 2016-09-02 10:37
@aqw Second that, just ran Kodi 17 with GP for the SEA game tonight w/o issues (international subscription w/o proxy/vpn). Could this cause @anthonyettinger's problem?

**Comment by BaumSchorle** [comment] 2016-09-02 10:40
To make this clear: we just need this special headers for live games!

So you guys need to test nfl network live for at least 10-15 minutes, to
check if its's working with Kodi 17.

Am 02.09.2016 12:38 nachm. schrieb "Stefan" <notifications@github.com>:

**Comment by Ghoschdi** [comment] 2016-09-02 10:43
@BaumSchorle: I watched the SEA game live tonight for the whole length.

**Comment by BaumSchorle** [comment] 2016-09-02 10:52
Are you running the latest Alpha? I hope for the best :)

**Comment by Ghoschdi** [comment] 2016-09-02 11:30
I ran the Beta, but now fetched the latest nightly and will run it in the background.  Will report back.

**Comment by Ghoschdi** [comment] 2016-09-02 18:45
Okay, latest nightly bugs throws the same error as @anthonyettinger mentioned before
`Unable to open key file http://nlsk.neulion.com/nlsk1/hls/securekey?`
After switching back to latest beta release, everything runs smooth again. As the commit was already added in Alpha 1, I do not understand why Beta 1 (which was released after Alpha 3) works and the latest nightly not. Maybe someone has an idea?

Will run a test on my shield TV as soon as I have the possibility.

**Comment by chovy** [comment] 2016-09-02 22:16
So I'm not crazy? Something broke in ffmpeg because I'm seeing the dropped key requests without even using Kodi.

**Comment by Ghoschdi** [comment] 2016-09-02 22:31
Well, Beta 1 including this commit seems to work including ffmpeg 3.1 and this commit. Have you tried Kodi Beta1?

**Comment by Ghoschdi** [comment] 2016-09-03 08:47
Tested with latest BETA Build from App Store on Shield TV. No issues running NFL Live for about 1.35h.

**Comment by basrieter** [comment] 2016-09-03 10:25
The only thing, http header related, is that user-agent and cookie are the only headers currently supported by Krypton's FFMpeg Demuxer. So if you use that one, there will be no problem.

**Comment by aqw** [comment] 2016-09-03 19:18
@basrieter Thanks for the info. IIRC, we only set the user agent and pass along cookie values. So I think Game Pass might (accidentally) thread the needle with Kodi's ffmpeg http header capability.

---Alex

**Comment by basrieter** [comment] 2016-09-03 19:22
I am trying to convince the Kodi dev that decided (by himself I guess) to disallow any other http headers that is change is not the one we need. See here: https://github.com/xbmc/xbmc/pull/9330

**Comment by Ghoschdi** [comment] 2016-11-06 09:01
Just found this while digging through the Kodi github. It seems like @basrieter succeeded: https://github.com/xbmc/xbmc/pull/10458

**Comment by DOGGYBONE** [comment] 2017-01-05 07:44
KODI 17 final release is out GamePass still not working still get not compatible message.

**Comment by Ghoschdi** [comment] 2017-01-05 13:12
There is still no stable release, only release candidates of Kodi 17.x 
You can download the zip from my 17.x branch over here:https://github.com/Ghoschdi/xbmc-gamepass/tree/Kodi-17.x , start Kodi and install from this zip. Should run fine.

**Comment by aqw** [comment] 2017-01-05 13:18
@Ghoschdi @DOGGYBONE I am working on this right now and will push some commits soon. If you (and others) would be willing to test it, then I can try to get this released for the weekend.

---Alex

**Comment by chovy** [comment] 2017-01-05 14:44
Is there anyway in kodi to log the generated ffmpeg command that is used to play a live stream?

**Comment by aqw** [comment] 2017-01-05 14:55
@chovy Please don't hijack issues. But, in answer to your question: no. Kodi handles talking with ffmpeg; we merely pass it the stream info, headers, and cookie. So we do not have the final ffmpeg command.

It sounds like you would like to use the streams independent of Kodi. We include a library called pigskin for that (though I know of no-one (other than this addon) which uses it). Though documentation is lacking, I imagine a motivated person could piece everything together in an hour or two.

If you run into problems or improvements, please open new issues for them. I'd be very happy to have another consumer of pigskin. I think it'll make the addon better and would open up some nice avenues for testing.

---Alex

**Comment by chovy** [comment] 2017-01-05 17:44
I wasn't hijacking the issue. I was trying to figure out how to see what ffmpeg is being executed so we can determine which http headers are missing that are supposed to be there for v17 to work.

**Comment by maddes-b** [comment] 2017-01-05 21:55
Got it working with LibreELEC 7.90.010 on Raspberry 3, that is Kodi 17.0-BETA7 Git:17.0-beta7-eed32e7.

**Comment by Ghoschdi** [comment] 2017-01-06 15:35
@aqw: Working on Shield TV so far. Will give it a full live try during Wildcards tomorrow.

**Comment by aqw** [comment] 2017-01-06 15:42
@chovy I think all those http header issues were resolved during the betas. I read through a few of the PRs and I think we're covered. If you run into problems, please be sure to open an issue.

@maddes-b @Ghoschdi Excellent. Thanks for the info!

---Alex

**Comment by Ghoschdi** [comment] 2017-01-08 12:45
@aqw: Worked perfectly during the complete 7 hours of wildcard games yesterday.

**Closed** 2017-01-09 14:19 UTC

**Comment by aqw** [comment] 2017-01-10 10:22
@Ghoschdi Excellent. Thanks for the report. :-)

I have submitted this release to the kodi devs. Should be accepted in the next day or two.

---Alex
