### ISSUE TITLE
Kodi 18 NFL Gamepass not working

### ISSUE THREAD

**Issue by pepcas** [aqw/xbmc-gamepass#422] opened 2019-03-10 10:16 UTC
I updated Kodi to version 18, but now NFL Game Pass it not working anymore, any idea to solve this?

Thank you.

**Comment by aqw** [comment] 2019-03-10 10:55
Closing as it is a duplicate of #373 

This addon will be updated before the 2019 season starts, but as I am currently changing jobs and moving, it won't be anytime in the immediate future.

---Alex

**Closed by aqw** 2019-03-10 10:55 UTC
Labels: duplicate, kodi-18
