### ISSUE TITLE
Australian NFL Game Pass holder can't play any content

### ISSUE THREAD

**Issue by SinclairHayes** [aqw/xbmc-gamepass#301] opened 2017-08-06 09:46 UTC
Firstly thank you for the plugin. I have just renewed my Game Pass for use in Australia and have tried to access it using your plugin. I have been able to bring up the interface but am unable to play any content. I've included the Kodi log file and a screenshot of what happens when I tried to access the recent Hall of Fame game.

I have also uninstalled/reinstalled the plugin using the zip file from this page as well

Again, thanks for your time and effort

[kodi.log.txt](https://github.com/aqw/xbmc-gamepass/files/1202981/kodi.log.txt)
![screen shot 2017-08-06 at 7 37 59 pm](https://user-images.githubusercontent.com/30769714/29002148-6392ce2a-7adf-11e7-9bc0-9ebb5fbc0f37.png)

**Comment by kaileu** [comment] 2017-08-06 10:29
Hi,
The Plugin in the Git Master is for Gamepass Europe at the moment.
Gamepass International which includes Australia isn't working because of the lag of International Developer.
See https://github.com/aqw/xbmc-gamepass/issues/299 and https://github.com/aqw/xbmc-gamepass/issues/294

**Comment by SinclairHayes** [comment] 2017-08-06 10:54
Hi,
Thank you for the reply and links. I hadn't read far enough into those posts, but I understand now what the issue is.
While sadly I know nothing about coding, if I can help at any point with testing, more than happy to.
Thanks again

**Comment by aqw** [comment] 2017-08-07 06:53
@SinclairHayes Yeah. Game Pass is really switching things up.

If you could, try downloading the 0.10.2 release [1]. There is a /chance/ it'll work for awhile longer. It also could be entirely broken by now. Who knows.

If 0.10.2 works for you, then I'll work to merge the old functionality back in, and we'll just ride that for as long as we can. If not, then we'll just have to continue waiting for someone with the right combo of skills, motivation, and geographic location to come along.

---Alex

[1] https://github.com/aqw/xbmc-gamepass/releases

**Comment by dav-sap** [comment] 2017-08-10 22:56
Hey, I'm using NFL game pass international. Having the same issue as stated above. the 0.10.2 release is totally broken, won't even start. I'll take a look at the issues maybe I can help

**Comment by gitquestion** [comment] 2017-08-11 00:21
Same issue here as well.  It may be that the url to access it changed to:  https://www.nflgamepass.com/

It was gamepass.nfl.com previously.

**Comment by kaileu** [comment] 2017-08-11 01:53
The whole API changed so no it won't help to just change the URL.

**Comment by slh1984** [comment] 2017-08-13 18:58
Hi does anyone know how to sort gamepass out version 10.2 is broken and have tried everything to sort it. Any help would be greatly appreciated thanks

**Comment by slh1984** [comment] 2017-08-13 19:09
Sorry I should have said I'm running 17.3 and have all the repos that are listed for it. Thanks again

**Comment by kaileu** [comment] 2017-08-13 19:11
If you are in Europe you have to install the master Version in Git.
The new Version isn't out in the Kodi repos.

Mit freundlichen Grüßen
Kai Leutner

**Comment by slh1984** [comment] 2017-08-13 19:15
Thanks for the help greatly appreciated. Where do I get the master version in git and how thanks again

**Comment by kaileu** [comment] 2017-08-13 19:25
https://github.com/aqw/xbmc-gamepass
In the right Corner cöone or download you have to download the current Master.
The you have to install addon from zip and point it to the downloaded version.

**Comment by slh1984** [comment] 2017-08-13 19:37
Thanks again, but i can't get the pull down menu from the clone or download section. I have downloaded the zip from the releases section and unzipped them on kodi but still won't open the add on.

**Comment by kaileu** [comment] 2017-08-13 19:38
https://github.com/aqw/xbmc-gamepass/archive/master.zip

**Comment by slh1984** [comment] 2017-08-13 19:53
Thanks your a legend so grateful. Get login error now any idea why thanks again so so thankful

**Comment by kaileu** [comment] 2017-08-13 19:56
Without Logfiles its hard to tell.
I guess you have not a valid Gamepass Europe Sunscription or are not allowed tu use GamePass Europe at your Location.

**Comment by slh1984** [comment] 2017-08-13 19:57
It's gamepass Europe I have and am in the UK. Thanks for all your help

**Comment by kaileu** [comment] 2017-08-13 20:00
So enable debug logging in the system settings and reproduce the error and then post a log file ;-)
https://www.kodinerds.net/index.php/Thread/7121-Wo-finde-ich-das-log-File-von-Kodi-XBMC/


Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment] 2017-08-14 11:15
Closing; See #313 

@slh1984 Please follow @kaileu's suggestion to use latest master. If you're still having problems, open a new issue and post a full debug log.

---Alex

**Closed by aqw** 2017-08-14 11:15 UTC
