### ISSUE TITLE
Unexpected error='(.Please enable debuging for both addon and Kodi??   WTF 

### ISSUE THREAD

**Issue by ShonKable** [aqw/xbmc-gamepass#332] opened 2017-08-23 01:15 UTC

**Comment by aia832003** [comment] 2017-08-23 01:32
I'm seeing this on Android but not the Linux client.

**Comment by ShonKable** [comment] 2017-08-23 01:33
I use android ??? Hopefully there is a fix and an update soon

**Comment by aia832003** [comment] 2017-08-23 01:38
Ok. I'm getting this on both clients now.

**Comment by ShonKable** [comment] 2017-08-23 01:39
Thx.. Im willing to donate and get that Cam Newton Version... : )

**Comment by kaileu** [comment] 2017-08-23 03:12
Install from master and wait on the pr to be merged.
Don't change the files by hand if you don't know what you are doing.

**Comment by ShonKable** [comment] 2017-08-23 03:14
pr ???

**Comment by kaileu** [comment] 2017-08-23 03:20
PR means Pull Request.
In other words wait till the fix is in the master version.
To manually edit files is not supported here.

**Comment by ShonKable** [comment] 2017-08-23 03:22
Ok thx sir, any time frame?

**Comment by aqw** [comment] 2017-08-23 06:52
Dupe of #330

**Closed by aqw** 2017-08-23 06:52 UTC
