### ISSUE TITLE
Red Zone Live still not working for me

### ISSUE THREAD

**Issue by redmanhsl** [aqw/xbmc-gamepass#353] opened 2017-09-19 10:46 UTC
Hello,
sorry I'm not an expert and don't know code.
I read that there's problems with Red Zone Live and some of you resolved it.
I still can't see it as of Sunday afternoon (Sept. 17). All the other games work and NFL Network too.
Is the fix coming in the next update?
Thanks

**Comment by kaileu** [comment] 2017-09-19 10:51
The fix is already included in the latest master https://github.com/aqw/xbmc-gamepass/archive/master.zip. If you are not able to install it from the master you have to wait till the next update is published to the repository.

**Comment by redmanhsl** [comment] 2017-09-19 11:59
First of all thank you for your reply. I do not know how to install it. Is it complicated?
Otherwise I guess I'll wait for the update. Any idea when that'll be?
Thanks again

**Comment by kaileu** [comment] 2017-09-19 18:25
Download zip, go to kodi addons install from zip and point it to the downloaded zip

**Comment by FahdW** [comment] 2017-09-21 17:17
Odd i installed the newest master to my Kodi and it still failed to work. Going to try again.

**Comment by kaileu** [comment] 2017-09-21 17:19
If its not working with the current Master.
Enable debugging reproduce the bug and upload a logfile.

**Comment by redmanhsl** [comment] 2017-09-25 08:08
Well I couldn't try before yesterday cause of the nature of the channel (appears only on Sunday afternoon). I wanna thank you cause I installed the latest master as suggested and explained by kaileu and it worked fine.

But did you guys have problems with the service yesterday? A lot of times it shut down. I don't think there was a problem with the add-on, cause it wasn't working from the app or the website either. It's like the servers where overloaded or something. It lasted for most the 1pm ET window.

**Comment by kaileu** [comment] 2017-09-25 08:39
Yes i had the same problem throughout all devices.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment] 2017-09-29 10:54
the nfl has sent an apology mail this week for the problems that occured on sunday, an incorrect configured server caused the problem.

btw whereis redzone to find on gamedays, i have the latest master installed, but cant see it

**Comment by kaileu** [comment] 2017-09-29 13:02
You find redzone in the NFL Network section next to NFL Network Live

Mit freundlichen Grüßen
Kai Leutner

**Comment by maddes-b** [comment] 2017-10-01 16:52
I can confirm that the current master (2017-10-01 16:00 CEST) works for NFL Redzone with Kodi 17.4 Krypton on Amazon Fire TV v2 with latest Fire OS 5.2.6.0 (587444320).

**Comment by aqw** [comment] 2018-08-12 07:34
Closing, as this issue seems to be resolved now. If not, please reopen and upload a debug log.

---Alex

**Closed by aqw** 2018-08-12 07:34 UTC
